// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyMessage_DataType int32

const (
	MyMessage_User            MyMessage_DataType = 0
	MyMessage_CreateRequest   MyMessage_DataType = 2
	MyMessage_CreateResponse  MyMessage_DataType = 3
	MyMessage_ReadRequest     MyMessage_DataType = 4
	MyMessage_ReadResponse    MyMessage_DataType = 5
	MyMessage_UpdateRequest   MyMessage_DataType = 6
	MyMessage_UpdateResponse  MyMessage_DataType = 7
	MyMessage_ReadAllRequest  MyMessage_DataType = 8
	MyMessage_ReadAllResponse MyMessage_DataType = 9
)

var MyMessage_DataType_name = map[int32]string{
	0: "User",
	2: "CreateRequest",
	3: "CreateResponse",
	4: "ReadRequest",
	5: "ReadResponse",
	6: "UpdateRequest",
	7: "UpdateResponse",
	8: "ReadAllRequest",
	9: "ReadAllResponse",
}

var MyMessage_DataType_value = map[string]int32{
	"User":            0,
	"CreateRequest":   2,
	"CreateResponse":  3,
	"ReadRequest":     4,
	"ReadResponse":    5,
	"UpdateRequest":   6,
	"UpdateResponse":  7,
	"ReadAllRequest":  8,
	"ReadAllResponse": 9,
}

func (x MyMessage_DataType) String() string {
	return proto.EnumName(MyMessage_DataType_name, int32(x))
}

func (MyMessage_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type MyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Permission           string   `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type CreateRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Task entity to add
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// ID of created task
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ReadRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// ID of created task
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReadRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ReadResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// ID of created task
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReadResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateRequest struct {
	// API versioning: it is my best practice to specify version explicitly
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Task entity to update
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// Contains status of update operation
type UpdateResponse struct {
	// API versioning: it is my best practice to specify version explicitly
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Contains number of entities have beed updated
	// Equals 1 in case of succesfull update
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ReadAllRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Pageno               int64    `protobuf:"varint,2,opt,name=pageno,proto3" json:"pageno,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

func (m *ReadAllRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReadAllRequest) GetPageno() int64 {
	if m != nil {
		return m.Pageno
	}
	return 0
}

func (m *ReadAllRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReadAllResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReadAllResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterEnum("service.MyMessage_DataType", MyMessage_DataType_name, MyMessage_DataType_value)
	proto.RegisterType((*MyMessage)(nil), "service.MyMessage")
	proto.RegisterType((*User)(nil), "service.User")
	proto.RegisterType((*CreateRequest)(nil), "service.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "service.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "service.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "service.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "service.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "service.UpdateResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "service.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "service.ReadAllResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb1, 0xe3, 0x24, 0x13, 0x42, 0xc3, 0x50, 0x5a, 0x13, 0x24, 0x54, 0x96, 0x0b, 0x27,
	0x1f, 0xda, 0x53, 0xa5, 0x0a, 0xf1, 0x51, 0xa1, 0x22, 0xd1, 0x8b, 0x49, 0xb9, 0xa2, 0x6d, 0x32,
	0xaa, 0x22, 0x1a, 0xef, 0xe2, 0xb5, 0x41, 0xfd, 0x53, 0xfc, 0x02, 0x7e, 0x17, 0x67, 0xb4, 0x5f,
	0xc1, 0x76, 0xe4, 0x43, 0x73, 0x4a, 0xe6, 0xcd, 0xdb, 0x37, 0x6f, 0x3e, 0x64, 0x98, 0xac, 0x49,
	0x29, 0x7e, 0x43, 0xa9, 0x2c, 0x44, 0x29, 0x70, 0xa0, 0xa8, 0xf8, 0xb9, 0x5a, 0x10, 0xfb, 0x13,
	0xc0, 0xe8, 0xf2, 0xee, 0xd2, 0x26, 0xd9, 0xef, 0x00, 0x86, 0xe7, 0xbc, 0xe4, 0xf3, 0x3b, 0x49,
	0x38, 0x84, 0xe8, 0x4a, 0x51, 0x31, 0x7d, 0x80, 0x8f, 0x61, 0xf2, 0xa1, 0x20, 0x5e, 0x52, 0x46,
	0x3f, 0x2a, 0x52, 0xe5, 0xb4, 0x87, 0x08, 0x8f, 0x3c, 0xa4, 0xa4, 0xc8, 0x15, 0x4d, 0x43, 0xdc,
	0x83, 0x71, 0x46, 0x7c, 0xe9, 0x49, 0x11, 0x4e, 0xe1, 0xa1, 0x05, 0x1c, 0xa5, 0xaf, 0x95, 0xae,
	0xe4, 0xb2, 0xa6, 0x14, 0x6b, 0x25, 0x0f, 0x39, 0xda, 0x40, 0x63, 0xfa, 0xe1, 0xbb, 0xdb, 0x5b,
	0xcf, 0x1b, 0xe2, 0x13, 0xd8, 0xdb, 0x60, 0x8e, 0x38, 0x62, 0x5f, 0xad, 0x47, 0x44, 0x88, 0x72,
	0xbe, 0xa6, 0x24, 0x38, 0x0a, 0x5e, 0x8f, 0x32, 0xf3, 0x1f, 0x67, 0x30, 0x94, 0x5c, 0xa9, 0x5f,
	0xa2, 0x58, 0x26, 0x3d, 0x83, 0x6f, 0x62, 0x7c, 0x01, 0x20, 0xa9, 0x58, 0xaf, 0x94, 0x5a, 0x89,
	0x3c, 0x09, 0x4d, 0xb6, 0x86, 0xb0, 0x8b, 0x56, 0xc7, 0xb8, 0x0f, 0xfd, 0x52, 0x7c, 0xa7, 0xdc,
	0x55, 0xb0, 0x01, 0xbe, 0x84, 0xa8, 0x52, 0x54, 0x18, 0xf9, 0xf1, 0xf1, 0x24, 0x75, 0x53, 0x4d,
	0xb5, 0xa7, 0xcc, 0xa4, 0xd8, 0x9b, 0xf6, 0xa0, 0x3a, 0xa4, 0x0e, 0x20, 0xd6, 0xfc, 0x4f, 0xd6,
	0x6b, 0x98, 0xb9, 0x88, 0x7d, 0x6c, 0x0c, 0x75, 0x77, 0x1f, 0x67, 0xcd, 0x5d, 0xdc, 0xd3, 0xc5,
	0x45, 0x6b, 0x6f, 0xbb, 0xfb, 0x78, 0xdb, 0x5e, 0x77, 0x87, 0x54, 0x02, 0x83, 0xca, 0xf0, 0xbc,
	0x15, 0x1f, 0xb2, 0x79, 0xfb, 0x38, 0xba, 0x7b, 0x91, 0xfc, 0x86, 0x72, 0xe1, 0x7b, 0xb1, 0x91,
	0x66, 0x2f, 0x44, 0x95, 0x97, 0x66, 0xed, 0x61, 0x66, 0x03, 0xf6, 0x79, 0xeb, 0xbc, 0x3a, 0x64,
	0x5f, 0x41, 0x5f, 0x37, 0xa2, 0x92, 0xde, 0x51, 0xb8, 0xdd, 0xa4, 0xcd, 0x1d, 0xff, 0x0d, 0x60,
	0x3c, 0x17, 0xe7, 0xe2, 0x8b, 0xcd, 0xe1, 0x29, 0xc4, 0xf6, 0x0a, 0xf0, 0x60, 0xc3, 0x6f, 0x1c,
	0xd8, 0xec, 0x70, 0x0b, 0x77, 0x2e, 0x4e, 0x20, 0xd2, 0xc6, 0x70, 0x7f, 0x43, 0xa8, 0xdd, 0xc3,
	0xec, 0x69, 0x0b, 0x75, 0x8f, 0x4e, 0x21, 0xb6, 0x53, 0xae, 0xd5, 0x6b, 0x2c, 0xb0, 0x56, 0xaf,
	0xb5, 0x8e, 0x33, 0x18, 0xb8, 0x41, 0xe0, 0x61, 0x43, 0xfc, 0xff, 0xc0, 0x67, 0xc9, 0x76, 0xc2,
	0xbe, 0x7e, 0xff, 0x1c, 0x9e, 0x2d, 0xc4, 0x3a, 0x5d, 0x56, 0xaa, 0x4c, 0xe5, 0xf5, 0x37, 0x4f,
	0x33, 0x5f, 0x9d, 0xeb, 0xd8, 0xfc, 0x9c, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x57, 0x33, 0xd4,
	0x06, 0x8d, 0x04, 0x00, 0x00,
}
